[package]
name = "retroboy-headless"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies.retroboy]
path = "../../"

[dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
image = "0.25"
